Repository elkarbackup/elkarbackup, pull requests merged in 2018-05, with the labels that each got.

#283 Migration modified to migrate correctly backup_dir param.
  app/DoctrineMigrations/Version20180207095757.php
Labels: kind/bug/fix

#292 Update parameters template (fixes #289)
  app/config/parameters.yml
  app/config/parameters.yml.dist
  app/config/parameters.yml.travis
  debian/DEBIAN/conffiles
  debian/DEBIAN/postinst
Labels: area/installer, kind/bug/fix

#293 Restore filenames with non-ascii chars - fixes #281
  src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
Labels: kind/bug/fix

#298 Alert messages related to client and job deletions
  src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
  src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js
Labels: area/backupjob, area/webui, kind/bug/fix
